### ISSUE TITLE
Trying to open an image from ms-appdata URI fails with cast exception

### ISSUE THREAD

**Issue by opi-smccoole** [phongcao/image-pipeline-windows#6] opened 2017-10-09 17:30 UTC
I'm using react-native-windows 0.48.0-rc.8 which uses version 0.0.6 of image-pipeline-windows and I am getting a cast exception when trying to open an image file with an ms-appdata URI.  Initially I was trying to open the image with a file URI (which used to work in react-native-windows 0.43 but now throws an unsupported URI type exception, that might qualify as another issue?).

The exception I get is:

System.InvalidCastException: 'Unable to cast object of type 'System.IO.DirectoryInfo' to type 'System.IO.FileInfo'.'

I believe this may be because of this code in ImageRequest.cs:

```
public FileSystemInfo SourceFile
        {
            get
            {
                lock (_gate)
                {
                    if (_sourceFile == null)
                    {
                        _sourceFile = new DirectoryInfo(SourceUri.LocalPath);
                    }

                    return _sourceFile;
                }
            }
        }
```

When I think it should be:
```
public FileSystemInfo SourceFile
        {
            get
            {
                lock (_gate)
                {
                    if (_sourceFile == null)
                    {
                        _sourceFile = new FileInfo(SourceUri.LocalPath);
                    }

                    return _sourceFile;
                }
            }
        }
```

**Comment by nmyhre** [comment] 2017-10-09 17:45
@opi-smccoole, @phongcao, I have a fix for this in a branch. The issue is the conversion from URI to a system filepath needs to be done by StorageFile.GetFileFromApplicationUriAsync in the UWP world. Let me generate a pull request and start the discussion about whether it is correct or not.

**Comment by opi-smccoole** [comment] 2017-10-09 19:08
I took a local fork and applied this change and manually moved the .dll files over into my react native app Debug directory and can confirm that these changes do fix the issue for me.  It would be great if some sort of fix could be arrived at so that it could be used in the upstream react-native-windows package since I'm at a standstill without the ability to load images from the file system.

**Comment by opi-smccoole** [comment] 2017-10-09 22:07
I created an example react-native-windows project that shows the issue here:

https://github.com/objectpartners/LocalImageBugExample

**Comment by phongcao** [comment] 2017-10-09 22:28
@opi-smccoole Thanks for reporting this issue. Look like there is missing some unit tests for **ms-appdata** uri that I need to add now. I'll release a new version of image-pipeline-windows soon.
@nmyhre Thanks for helping! I'll check your PR as soon as all of the necessary unit tests for **ms-appdata** uri have been added.

**Closed** 2017-10-10 13:46 UTC
